services:
  postgres:
    image: postgres:15
    container_name: ged-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ged_database
      POSTGRES_USER: ged_user
      POSTGRES_PASSWORD: ged_password_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - ged-network

  # Optionnel: pgAdmin pour l'administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ged-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ged.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ged-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ged-network:
    driver: bridge
